name: Build Binary on Main

on:
  push:
    branches:
      - main
  workflow_dispatch: # 手动触发
  pull_request:
    branches: [main] # 在 PR 提交到 main 时触发

jobs:
  build-binary:
    uses: ./.github/workflows/build-binary.yml

